// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyFileVersion("2.0.0.0")]
[assembly: AssemblyInformationalVersion("")]
[assembly: AssemblyProduct("Basisregisters Vlaanderen")]
[assembly: AssemblyCopyright("Copyright (c) Vlaamse overheid")]
[assembly: AssemblyCompany("Vlaamse overheid")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "2.0.0.0";
        internal const System.String AssemblyFileVersion = "2.0.0.0";
        internal const System.String AssemblyInformationalVersion = "";
        internal const System.String AssemblyProduct = "Basisregisters Vlaanderen";
        internal const System.String AssemblyCopyright = "Copyright (c) Vlaamse overheid";
        internal const System.String AssemblyCompany = "Vlaamse overheid";
    }
}
