// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("2.0.0.0")]
[assembly: AssemblyFileVersionAttribute("2.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("")]
[assembly: AssemblyProductAttribute("Basisregisters Vlaanderen")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Vlaamse overheid")]
[assembly: AssemblyCompanyAttribute("Vlaamse overheid")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "2.0.0.0";
        internal const System.String AssemblyFileVersion = "2.0.0.0";
        internal const System.String AssemblyInformationalVersion = "";
        internal const System.String AssemblyProduct = "Basisregisters Vlaanderen";
        internal const System.String AssemblyCopyright = "Copyright (c) Vlaamse overheid";
        internal const System.String AssemblyCompany = "Vlaamse overheid";
    }
}
