CREATE OR REPLACE STREAM IF NOT EXISTS ADDRESS_SNAPSHOT_OSLO_STREAM_FLATTEN_INTEGRATIONDB
WITH (KAFKA_TOPIC='address.snapshot.oslo.flatten.integrationdb', PARTITIONS=1, VALUE_FORMAT='JSON_SR', KEY_FORMAT='JSON_SR')
AS 
SELECT
  CAST(REDUCE(SPLIT(URL_EXTRACT_PATH(MESSAGEKEY), '/'), '', (s,x) => x) AS INT) PersistentLocalId,

  CAST(GEMEENTE->OBJECTID AS INT) AS "NisCode",
  POSTINFO->OBJECTID as "PostalCode",
  CAST(STRAATNAAM->OBJECTID AS INT) as "StreetNamePersistentLocalId",
  ADRESSTATUS as "Status",
  HUISNUMMER as "HouseNumber",
  BUSNUMMER as "BoxNumber",
  VOLLEDIGADRES->GEOGRAFISCHENAAM->SPELLING as "FullName",
  ADRESPOSITIE->GEOMETRIE->GML as "GeometryGml",
  ADRESPOSITIE->POSITIEGEOMETRIEMETHODE as "PositionMethod",
  ADRESPOSITIE->POSITIESPECIFICATIE as "PositionSpecification",
  OFFICIEELTOEGEKEND as "IsOfficiallyAssigned",

  IDENTIFICATOR->ID as "PuriId",
  IDENTIFICATOR->NAAMRUIMTE as "Namespace",
  IDENTIFICATOR->VERSIEID as "VersionString",
  PARSE_TIMESTAMP(IDENTIFICATOR->VERSIEID, 'yyyy-MM-dd''T''HH:mm:ssXXX', 'UTC') as "VersionTimestamp",
  CAST(FROM_BYTES(FILTER(headers, (x) => (x->key = 'IdempotenceKey'))[1]->VALUE, 'utf8') AS BIGINT) as "IdempotenceKey",
  CASE WHEN IDENTIFICATOR->ID is null THEN TRUE ELSE FALSE END as "IsRemoved"

FROM ADDRESS_SNAPSHOT_OSLO_STREAM_V2
PARTITION BY CAST(REDUCE(SPLIT(URL_EXTRACT_PATH(MESSAGEKEY), '/'), '', (s,x) => x) AS INT);