// <auto-generated />
using System;
using AddressRegistry.Projections.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AddressRegistry.Projections.Api.Migrations
{
    [DbContext(typeof(ApiContext))]
    partial class ApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AddressRegistry.Projections.Api.AddressDetail.AddressDetailItem", b =>
                {
                    b.Property<int>("AddressPersistentLocalId")
                        .HasColumnType("integer");

                    b.Property<string>("BoxNumber")
                        .HasColumnType("text");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastEventHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OfficiallyAssigned")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentAddressPersistentLocalId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Position")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("PositionMethod")
                        .HasColumnType("integer");

                    b.Property<int>("PositionSpecification")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StreetNamePersistentLocalId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("VersionTimestampAsDateTimeOffset")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VersionTimestamp");

                    b.HasKey("AddressPersistentLocalId")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("BoxNumber");

                    b.HasIndex("HouseNumber");

                    b.HasIndex("PostalCode");

                    b.HasIndex("Removed");

                    b.HasIndex("Status");

                    b.HasIndex("StreetNamePersistentLocalId");

                    b.HasIndex("VersionTimestampAsDateTimeOffset");

                    b.ToTable("AddressDetails", "AddressRegistryApi");
                });

            modelBuilder.Entity("AddressRegistry.Projections.Api.AddressSyndication.AddressBoxNumberSyndicationHelper", b =>
                {
                    b.Property<int>("PersistentLocalId")
                        .HasColumnType("integer");

                    b.Property<string>("BoxNumber")
                        .HasColumnType("text");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOfficiallyAssigned")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("PointPosition")
                        .HasColumnType("bytea");

                    b.Property<int?>("PositionMethod")
                        .HasColumnType("integer");

                    b.Property<int?>("PositionSpecification")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.HasKey("PersistentLocalId")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("AddressBoxNumberSyndicationHelper", "AddressRegistryApi");
                });

            modelBuilder.Entity("AddressRegistry.Projections.Api.AddressSyndication.AddressSyndicationItem", b =>
                {
                    b.Property<long>("FeedPosition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FeedPosition"));

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Application")
                        .HasColumnType("integer");

                    b.Property<string>("BoxNumber")
                        .HasColumnType("text");

                    b.Property<string>("ChangeType")
                        .HasColumnType("text");

                    b.Property<string>("EventDataAsXml")
                        .HasColumnType("text");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOfficiallyAssigned")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastChangedOnAsDateTimeOffset")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastChangedOn");

                    b.Property<int?>("Modification")
                        .HasColumnType("integer");

                    b.Property<string>("Operator")
                        .HasColumnType("text");

                    b.Property<int?>("Organisation")
                        .HasColumnType("integer");

                    b.Property<int?>("PersistentLocalId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("PointPosition")
                        .HasColumnType("bytea");

                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.Property<int?>("PositionMethod")
                        .HasColumnType("integer");

                    b.Property<int?>("PositionSpecification")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RecordCreatedAtAsDateTimeOffset")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RecordCreatedAt");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StreetNameId")
                        .HasColumnType("uuid");

                    b.Property<int?>("StreetNamePersistentLocalId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SyndicationItemCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FeedPosition")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("AddressId");

                    b.HasIndex("FeedPosition");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FeedPosition"), "brin");

                    b.HasIndex("PersistentLocalId");

                    b.HasIndex("Position");

                    b.ToTable("AddressSyndication", "AddressRegistryApi");
                });

            modelBuilder.Entity("Be.Vlaanderen.Basisregisters.ProjectionHandling.Runner.ProjectionStates.ProjectionStateItem", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("DesiredState")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DesiredStateChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.HasKey("Name");

                    b.ToTable("ProjectionStates", "AddressRegistryApi");
                });
#pragma warning restore 612, 618
        }
    }
}
